site_name: VS Code Documentation for Beginner

nav:
  - Home: "index.md"
  - Debugging: "pages/debugging.md"
  - Connecting to GitHub: "pages/connect-github.md"
  - Editing Code Efficiently: "pages/code.md"
  - Troubleshooting: "pages/troubleshooting.md"
  - Glossary: "pages/glossary.md"

theme:
  name: material
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue

    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue
  
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist


repo_url: https://github.com/shinyoungyou/user-docs
repo_name: shinyoungyou/user-docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shinyoungyou/user-docs
      name: GitHub


copyright: Copyright &copy; 2025 - Shinyoung You & Zoey Lee